import { useCallback, useEffect, useState } from "react";
import { get, post, put, remove } from "../api";
import { EmptyState, Notice, PageHeader, StatusBadge } from "../AdminLayout";

const slugify=(value)=>String(value||"").toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/(^-+|-+$)/g,"");

export function BrandsPage(){
  const [brands,setBrands]=useState([]),[categories,setCategories]=useState([]),[search,setSearch]=useState(""),[editing,setEditing]=useState(null),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const [b,c]=await Promise.all([get(`/admin/brands?limit=100&search=${encodeURIComponent(search)}`),get("/admin/categories")]);setBrands(b);setCategories(c.filter((item)=>item.parent_id&&item.uses_brand));},[search]);
  useEffect(()=>{load().catch((e)=>setNotice(e.message));},[load]);
  const save=async(event)=>{event.preventDefault();const form=new FormData(event.currentTarget),body={name:form.get("name"),slug:form.get("slug"),is_active:form.get("active")==="on",category_ids:form.getAll("category_ids").map(Number)};if(editing?.id)await put(`/admin/brands/${editing.id}`,body);else await post("/admin/brands",body);setEditing(null);setNotice("Brand saved.");load();};
  const destroy=async(brand)=>{if(!window.confirm(`Delete ${brand.name}? Referenced brands must be deactivated instead.`))return;try{await remove(`/admin/brands/${brand.id}`);setNotice("Brand deleted.");load();}catch(e){setNotice(e.message);}};
  return <><PageHeader eyebrow="Catalog" title="Brands" description="One reusable brand record can be assigned to multiple component categories." actions={<button className="admin-button primary" type="button" onClick={()=>setEditing({is_active:true,categories:[]})}>Add Brand</button>}/><Notice message={notice} onClose={()=>setNotice("")}/><div className="admin-toolbar"><input className="admin-input" placeholder="Search brands" value={search} onChange={(e)=>setSearch(e.target.value)}/></div>
  <div className="admin-table-wrap admin-panel">{brands.length?<table className="admin-table"><thead><tr><th>Brand</th><th>Assigned Categories</th><th>Models</th><th>Status</th><th>Actions</th></tr></thead><tbody>{brands.map((brand)=><tr key={brand.id}><td><b>{brand.name}</b><small>{brand.slug}</small></td><td>{brand.categories?.map((c)=><span className="admin-chip" key={c.id}>{c.name}</span>)}</td><td>{brand.model_count}</td><td><StatusBadge active={brand.is_active}/></td><td><button className="admin-link-button" type="button" onClick={()=>setEditing(brand)}>Edit</button><button className="admin-link-button danger" type="button" onClick={()=>destroy(brand)}>Delete</button></td></tr>)}</tbody></table>:<EmptyState title="No brands found"/>}</div>{editing?<BrandModal brand={editing} categories={categories} onClose={()=>setEditing(null)} onSave={save}/>:null}</>;
}

function BrandModal({brand,categories,onClose,onSave}){const [name,setName]=useState(brand.name||"");return <div className="admin-modal-backdrop" role="presentation"><div className="admin-modal" role="dialog" aria-modal="true" aria-labelledby="brand-modal-title"><div className="admin-modal-head"><h2 id="brand-modal-title">{brand.id?"Edit":"Add"} Brand</h2><button type="button" onClick={onClose} aria-label="Close">×</button></div><form onSubmit={onSave}><label>Brand Name<input name="name" required maxLength="255" value={name} onChange={(e)=>setName(e.target.value)}/></label><label>Slug / Code<input name="slug" required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" defaultValue={brand.slug||slugify(name)}/></label><fieldset><legend>Assigned categories</legend><div className="admin-checkbox-grid">{categories.map((category)=><label key={category.id}><input type="checkbox" name="category_ids" value={category.id} defaultChecked={brand.categories?.some((item)=>item.id===category.id)}/><span>{category.name}<small>{category.system_type}</small></span></label>)}</div></fieldset><label className="admin-check"><input type="checkbox" name="active" defaultChecked={brand.is_active!==false}/>Active</label><div className="admin-modal-actions"><button className="admin-button secondary" type="button" onClick={onClose}>Cancel</button><button className="admin-button primary" type="submit">Save Brand</button></div></form></div></div>;}

export function ProductsPage({accessoriesOnly=false}){
  const [products,setProducts]=useState([]),[categories,setCategories]=useState([]),[brands,setBrands]=useState([]),[filters,setFilters]=useState({search:"",system:"",categoryId:"",brandId:"",active:"true"}),[editing,setEditing]=useState(null),[notice,setNotice]=useState("");
  const load=useCallback(async()=>{const query=new URLSearchParams({...filters,limit:"100"});const [p,c,b]=await Promise.all([get(`/admin/products?${query}`),get("/admin/categories"),get("/admin/brands?limit=100")]);setProducts(accessoriesOnly?p.filter((item)=>String(item.component_type).includes("accessor")):p);setCategories(c.filter((item)=>item.parent_id));setBrands(b);},[filters,accessoriesOnly]);useEffect(()=>{load().catch((e)=>setNotice(e.message));},[load]);
  const change=(key)=>(event)=>setFilters((old)=>({...old,[key]:event.target.value}));
  const save=async(event)=>{event.preventDefault();const f=new FormData(event.currentTarget),metadata=JSON.parse(f.get("metadata")||"{}");const body={name:f.get("name"),model:f.get("model"),sku:f.get("sku"),unit:f.get("unit"),category_id:Number(f.get("category_id")),brand_id:f.get("brand_id")?Number(f.get("brand_id")):null,is_active:f.get("active")==="on",technical_metadata:metadata};if(editing?.id)await put(`/admin/products/${editing.id}`,body);else await post("/admin/products",body);setEditing(null);setNotice("Product saved.");load();};
  const destroy=async(product)=>{if(!window.confirm(`Delete ${product.model||product.name}? Historical references will block deletion.`))return;try{await remove(`/admin/products/${product.id}`);setNotice("Product deleted.");load();}catch(e){setNotice(e.message);}};
  return <><PageHeader eyebrow="Catalog" title={accessoriesOnly?"Accessories":"Products & Models"} description="Shared master products retain structured fields and complete technical JSONB metadata." actions={<button className="admin-button primary" type="button" onClick={()=>setEditing({is_active:true,technical_metadata:{}})}>Add Model</button>}/><Notice message={notice} onClose={()=>setNotice("")}/><div className="admin-toolbar filters"><input className="admin-input" placeholder="Search model or product" value={filters.search} onChange={change("search")}/><select value={filters.system} onChange={change("system")}><option value="">All systems</option><option value="led-display">LED Display</option><option value="rental-led">Rental LED</option><option value="pa-system">PA System</option><option value="conference-system">Conference System</option></select><select value={filters.categoryId} onChange={change("categoryId")}><option value="">All categories</option>{categories.map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={filters.brandId} onChange={change("brandId")}><option value="">All brands</option>{brands.map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></div>
  <div className="admin-table-wrap admin-panel">{products.length?<table className="admin-table"><thead><tr><th>Model</th><th>Brand</th><th>System / Category</th><th>Unit</th><th>Status</th><th>Actions</th></tr></thead><tbody>{products.map((p)=><tr key={p.id}><td><b>{p.model||p.name}</b><small>{p.name}</small></td><td>{p.brand_name||"—"}</td><td>{p.system_type}<small>{p.category_name}</small></td><td>{p.unit}</td><td><StatusBadge active={p.is_active}/></td><td><button className="admin-link-button" type="button" onClick={()=>setEditing(p)}>Edit</button><button className="admin-link-button danger" type="button" onClick={()=>destroy(p)}>Delete</button></td></tr>)}</tbody></table>:<EmptyState title="No models match these filters"/>}</div>{editing?<ProductModal product={editing} categories={categories} brands={brands} onClose={()=>setEditing(null)} onSave={save}/>:null}</>;
}

function ProductModal({product,categories,brands,onClose,onSave}){const [categoryId,setCategoryId]=useState(String(product.category_id||""));const category=categories.find((item)=>String(item.id)===categoryId);return <div className="admin-modal-backdrop"><div className="admin-modal wide" role="dialog" aria-modal="true"><div className="admin-modal-head"><h2>{product.id?"Edit":"Add"} Product / Model</h2><button type="button" onClick={onClose} aria-label="Close">×</button></div><form onSubmit={onSave}><div className="admin-form-grid"><label>Product Name<input name="name" required defaultValue={product.name}/></label><label>Model<input name="model" defaultValue={product.model}/></label><label>SKU<input name="sku" defaultValue={product.sku}/></label><label>Unit<input name="unit" required defaultValue={product.unit||"Nos."}/></label><label>Category<select name="category_id" required value={categoryId} onChange={(e)=>setCategoryId(e.target.value)}><option value="">Select category</option>{categories.map((c)=><option key={c.id} value={c.id}>{c.system_type} — {c.name}</option>)}</select></label>{category?.uses_brand!==false?<label>Brand<select name="brand_id" required defaultValue={product.brand_id||""}><option value="">Select brand</option>{brands.filter((b)=>b.categories?.some((c)=>c.id===Number(categoryId))).map((b)=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>:<div className="admin-no-brand-note"><b>No brand required</b><span>Rental LED categories intentionally skip brands.</span></div>}</div><label>Technical metadata (JSON)<textarea name="metadata" rows="9" defaultValue={JSON.stringify(product.technical_metadata||{},null,2)}/></label><label className="admin-check"><input type="checkbox" name="active" defaultChecked={product.is_active!==false}/>Active</label><div className="admin-modal-actions"><button className="admin-button secondary" type="button" onClick={onClose}>Cancel</button><button className="admin-button primary" type="submit">Save Model</button></div></form></div></div>;}
