import { useCallback, useEffect, useState } from "react";
import { get, post, put } from "../api";
import { EmptyState, Notice, PageHeader, StatusBadge } from "../AdminLayout";
import { useCompany } from "../contexts";

// Platinum and Diamond are calculated from Gold in the quotation calculator.
// They are intentionally not stored or edited as independent prices here.
const tiers=["default","cob"];

export function CompanyPricesPage(){
  const {companyId,company}=useCompany();
  const [rows,setRows]=useState([]),[search,setSearch]=useState(""),[editing,setEditing]=useState(null),[notice,setNotice]=useState("");
  const multiplier=Number(company?.pricing_multiplier)||1;
  const derived=Boolean(company?.pricing_source_company_id)&&multiplier!==1;
  const load=useCallback(()=>companyId?get(`/admin/prices?companyId=${companyId}&limit=100&search=${encodeURIComponent(search)}`).then(setRows):Promise.resolve(),[companyId,search]);
  useEffect(()=>{load().catch((e)=>setNotice(e.message));},[load]);
  const save=async(event)=>{event.preventDefault();const f=new FormData(event.currentTarget),prices={};tiers.forEach((tier)=>{if(f.get(tier)!=="")prices[tier]=f.get(tier);});await put(`/admin/prices/${editing.id}`,{company_id:Number(companyId),prices});setEditing(null);setNotice("Company prices updated.");load();};
  const description=derived?`${company?.name} prices are calculated automatically from Mugnee at x${multiplier.toFixed(2)}.`:`${company?.name||"Selected company"} prices applied to one shared product catalog.`;
  return <><PageHeader eyebrow="Pricing" title="Company Prices" description={description}/><Notice message={notice} onClose={()=>setNotice("")}/><div className="admin-toolbar"><input className="admin-input" placeholder="Search models" value={search} onChange={(e)=>setSearch(e.target.value)}/><span className="admin-context-pill">{company?.name}{derived?` · x${multiplier.toFixed(2)}`:""}</span></div><div className="admin-table-wrap admin-panel">{rows.length?<table className="admin-table price-table"><thead><tr><th>SL No.</th><th>Model</th><th>Brand</th><th>Category</th>{tiers.slice(0,4).map((tier)=><th key={tier}>{tier[0].toUpperCase()+tier.slice(1)}</th>)}<th>Last Updated</th><th>Edit</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.id}><td>{index+1}</td><td><b>{row.model||row.name}</b><small>{row.name}</small></td><td>{row.brand||"—"}</td><td>{row.category||"—"}</td>{tiers.slice(0,4).map((tier)=><td key={tier}>{row.prices?.[tier]!==undefined?`৳ ${Number(row.prices[tier]).toLocaleString()}`:"—"}</td>)}<td>{row.last_updated?new Date(row.last_updated).toLocaleDateString():"—"}</td><td>{derived?<span>Auto</span>:<button className="admin-link-button" type="button" onClick={()=>setEditing(row)}>Edit</button>}</td></tr>)}</tbody></table>:<EmptyState title="No company prices" description="Add prices to the shared Mugnee product catalog."/>}</div>{editing&&!derived?<PriceModal row={editing} company={company} onClose={()=>setEditing(null)} onSave={save}/>:null}</>;
}

function PriceModal({row,company,onClose,onSave}){return <div className="admin-modal-backdrop"><div className="admin-modal" role="dialog" aria-modal="true"><div className="admin-modal-head"><div><h2>Edit Prices</h2><p>{row.model||row.name} · {company?.name}</p></div><button type="button" onClick={onClose}>×</button></div><form onSubmit={onSave}><div className="admin-form-grid">{tiers.map((tier)=><label key={tier}>{tier[0].toUpperCase()+tier.slice(1)}<input type="number" min="0" step="0.0001" name={tier} defaultValue={row.prices?.[tier]??""}/></label>)}</div><div className="admin-modal-actions"><button className="admin-button secondary" type="button" onClick={onClose}>Cancel</button><button className="admin-button primary" type="submit">Save Prices</button></div></form></div></div>}

export function BulkPricesPage(){const {companies,companyId}=useCompany();const [operation,setOperation]=useState("percentage"),[destination,setDestination]=useState(""),[percentage,setPercentage]=useState(""),[preview,setPreview]=useState(null),[notice,setNotice]=useState("");const body=operation==="copy"?{operation,source_company_id:Number(companyId),destination_company_id:Number(destination)}:{operation,company_id:Number(companyId),percentage:Number(percentage)};const getPreview=async()=>{setPreview(await post("/admin/prices/bulk-preview",body));};const apply=async()=>{if(!window.confirm(`Apply this bulk update to ${preview?.affected_count||0} prices? This cannot be automatically undone.`))return;const result=await post("/admin/prices/bulk-apply",{...body,confirm:true});setNotice(`${result.updated} prices updated.`);setPreview(null);};return <><PageHeader eyebrow="Pricing" title="Bulk Price Update" description="Preview every bulk operation and require explicit confirmation before applying it."/><Notice message={notice} onClose={()=>setNotice("")}/><section className="admin-panel admin-form-panel"><div className="admin-segmented"><button type="button" className={operation==="percentage"?"active":""} onClick={()=>{setOperation("percentage");setPreview(null);}}>Percentage adjustment</button><button type="button" className={operation==="copy"?"active":""} onClick={()=>{setOperation("copy");setPreview(null);}}>Copy company prices</button></div>{operation==="percentage"?<label>Increase or decrease by percentage<input type="number" min="-99.99" max="1000" step="0.01" value={percentage} onChange={(e)=>setPercentage(e.target.value)} placeholder="Example: 5 or -3"/></label>:<label>Destination company<select value={destination} onChange={(e)=>setDestination(e.target.value)}><option value="">Select company</option>{companies.filter((c)=>String(c.id)!==String(companyId)).map((c)=><option key={c.id} value={c.id}>{c.name}</option>)}</select><small>Existing destination prices will not be overwritten.</small></label>}<button className="admin-button primary" type="button" disabled={operation==="copy"?!destination:percentage===""} onClick={getPreview}>Preview changes</button>{preview?<div className="bulk-preview"><h3>Preview</h3><div><strong>{preview.affected_count}</strong><span>source prices</span></div>{operation==="copy"?<div><strong>{preview.existing_destination_count}</strong><span>existing destination prices skipped</span></div>:null}<button className="admin-button danger" type="button" onClick={apply}>Confirm and apply</button></div>:null}</section></>}

export function PricingTiersPage(){const [rows,setRows]=useState([]),[notice,setNotice]=useState("");const load=()=>get("/admin/pricing-tiers").then(setRows);useEffect(()=>{load().catch((e)=>setNotice(e.message));},[]);const toggle=async(row)=>{await put(`/admin/pricing-tiers/${row.id}`,{...row,is_active:!row.is_active});setNotice("Pricing tier updated.");load();};return <><PageHeader eyebrow="Pricing" title="Pricing Tiers" description="Existing calculator tiers remain aligned with Gold, Platinum, Diamond, and product-specific variants."/><Notice message={notice}/><div className="admin-table-wrap admin-panel"><table className="admin-table"><thead><tr><th>SL No.</th><th>Tier</th><th>Description</th><th>Warranty</th><th>Status</th><th>Actions</th></tr></thead><tbody>{rows.map((row,index)=><tr key={row.id}><td>{index+1}</td><td><b>{row.name}</b><small>{row.code}</small></td><td>{row.description}</td><td>{row.warranty_years?`${row.warranty_years} years`:"—"}</td><td><StatusBadge active={row.is_active}/></td><td><button className="admin-link-button" type="button" onClick={()=>toggle(row)}>{row.is_active?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table></div></>}
