BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
  version text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS companies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  code text NOT NULL UNIQUE,
  logo text,
  address text,
  phone text,
  email text,
  website text,
  is_default boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS companies_one_default_idx ON companies (is_default) WHERE is_default;

CREATE TABLE IF NOT EXISTS products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_key text NOT NULL UNIQUE,
  sku text,
  category text NOT NULL,
  component_type text,
  name text NOT NULL,
  brand text,
  model text,
  unit text NOT NULL DEFAULT 'Nos.',
  currency char(3) NOT NULL DEFAULT 'BDT',
  technical_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  source_catalog text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS products_category_idx ON products (category);
CREATE INDEX IF NOT EXISTS products_component_type_idx ON products (component_type);
CREATE INDEX IF NOT EXISTS products_brand_model_idx ON products (brand, model);
CREATE INDEX IF NOT EXISTS products_metadata_gin_idx ON products USING gin (technical_metadata);

CREATE TABLE IF NOT EXISTS company_product_prices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  price_tier text NOT NULL DEFAULT 'default',
  unit_price numeric(16,4) NOT NULL CHECK (unit_price >= 0),
  cost_price numeric(16,4) CHECK (cost_price IS NULL OR cost_price >= 0),
  currency char(3) NOT NULL DEFAULT 'BDT',
  pricing_metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_id, product_id, price_tier)
);
CREATE INDEX IF NOT EXISTS company_product_prices_lookup_idx
  ON company_product_prices (company_id, product_id) WHERE is_active;

CREATE TABLE IF NOT EXISTS calculator_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  calculator_type text NOT NULL,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_id, calculator_type)
);

CREATE TABLE IF NOT EXISTS quotation_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL UNIQUE REFERENCES companies(id) ON DELETE CASCADE,
  quotation_prefix text NOT NULL,
  header_information jsonb NOT NULL DEFAULT '{}'::jsonb,
  footer_information jsonb NOT NULL DEFAULT '{}'::jsonb,
  terms jsonb NOT NULL DEFAULT '[]'::jsonb,
  branding jsonb NOT NULL DEFAULT '{}'::jsonb,
  default_validity_days integer CHECK (default_validity_days IS NULL OR default_validity_days >= 0),
  default_delivery_period text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS invoice_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL UNIQUE REFERENCES companies(id) ON DELETE CASCADE,
  invoice_prefix text NOT NULL,
  template_key text NOT NULL,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quotations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quotation_number text NOT NULL,
  company_id bigint NOT NULL REFERENCES companies(id),
  client_name text,
  client_information jsonb NOT NULL DEFAULT '{}'::jsonb,
  calculator_type text NOT NULL,
  currency char(3) NOT NULL DEFAULT 'BDT',
  subtotal numeric(16,4) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  vat_amount numeric(16,4) NOT NULL DEFAULT 0 CHECK (vat_amount >= 0),
  discount_amount numeric(16,4) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
  grand_total numeric(16,4) NOT NULL DEFAULT 0 CHECK (grand_total >= 0),
  status text NOT NULL DEFAULT 'draft',
  created_by text,
  snapshot_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_id, quotation_number)
);
CREATE INDEX IF NOT EXISTS quotations_company_created_idx ON quotations (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS quotations_status_idx ON quotations (status);

CREATE TABLE IF NOT EXISTS quotation_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quotation_id bigint NOT NULL REFERENCES quotations(id) ON DELETE CASCADE,
  product_id bigint REFERENCES products(id) ON DELETE SET NULL,
  line_number integer NOT NULL CHECK (line_number > 0),
  item_description text NOT NULL,
  model_description text,
  quantity numeric(16,4) NOT NULL CHECK (quantity >= 0),
  unit text NOT NULL,
  unit_price numeric(16,4) NOT NULL CHECK (unit_price >= 0),
  total_price numeric(16,4) NOT NULL CHECK (total_price >= 0),
  snapshot_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (quotation_id, line_number)
);

CREATE TABLE IF NOT EXISTS invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number text NOT NULL,
  company_id bigint NOT NULL REFERENCES companies(id),
  quotation_id bigint REFERENCES quotations(id) ON DELETE SET NULL,
  client_name text,
  client_information jsonb NOT NULL DEFAULT '{}'::jsonb,
  currency char(3) NOT NULL DEFAULT 'BDT',
  subtotal numeric(16,4) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
  vat_amount numeric(16,4) NOT NULL DEFAULT 0 CHECK (vat_amount >= 0),
  discount_amount numeric(16,4) NOT NULL DEFAULT 0 CHECK (discount_amount >= 0),
  grand_total numeric(16,4) NOT NULL DEFAULT 0 CHECK (grand_total >= 0),
  status text NOT NULL DEFAULT 'draft',
  issued_at timestamptz,
  due_at timestamptz,
  created_by text,
  snapshot_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_id, invoice_number)
);
CREATE INDEX IF NOT EXISTS invoices_company_created_idx ON invoices (company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS invoices_status_idx ON invoices (status);

CREATE TABLE IF NOT EXISTS invoice_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_id bigint NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  product_id bigint REFERENCES products(id) ON DELETE SET NULL,
  line_number integer NOT NULL CHECK (line_number > 0),
  item_description text NOT NULL,
  model_description text,
  quantity numeric(16,4) NOT NULL CHECK (quantity >= 0),
  unit text NOT NULL,
  unit_price numeric(16,4) NOT NULL CHECK (unit_price >= 0),
  total_price numeric(16,4) NOT NULL CHECK (total_price >= 0),
  snapshot_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (invoice_id, line_number)
);

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['companies','products','company_product_prices','calculator_settings','quotation_settings','invoice_settings','quotations','invoices']
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I_updated_at ON %I', table_name, table_name);
    EXECUTE format('CREATE TRIGGER %I_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()', table_name, table_name);
  END LOOP;
END $$;

COMMIT;
