BEGIN;

CREATE TABLE IF NOT EXISTS roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  code text NOT NULL UNIQUE,
  description text,
  is_system boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS permissions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  description text NOT NULL
);

CREATE TABLE IF NOT EXISTS role_permissions (
  role_id bigint NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
  permission_id bigint NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
  PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  display_name text NOT NULL,
  password_hash text NOT NULL,
  role_id bigint NOT NULL REFERENCES roles(id),
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamptz,
  password_changed_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS users_username_lower_idx ON users (lower(username));

CREATE TABLE IF NOT EXISTS auth_sessions (
  id uuid PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash char(64) NOT NULL UNIQUE,
  csrf_token_hash char(64) NOT NULL,
  expires_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  user_agent text,
  ip_address inet,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS auth_sessions_expiry_idx ON auth_sessions (expires_at);
CREATE INDEX IF NOT EXISTS auth_sessions_user_idx ON auth_sessions (user_id);

CREATE TABLE IF NOT EXISTS categories (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id bigint REFERENCES categories(id) ON DELETE RESTRICT,
  system_type text NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  uses_brand boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  specifications_schema jsonb NOT NULL DEFAULT '{}'::jsonb,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (system_type, slug)
);
CREATE INDEX IF NOT EXISTS categories_parent_idx ON categories (parent_id, sort_order);

CREATE TABLE IF NOT EXISTS brands (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS brands_name_lower_idx ON brands (lower(name));

CREATE TABLE IF NOT EXISTS category_brands (
  category_id bigint NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  brand_id bigint NOT NULL REFERENCES brands(id) ON DELETE RESTRICT,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (category_id, brand_id)
);

ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id bigint REFERENCES categories(id) ON DELETE RESTRICT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS brand_id bigint REFERENCES brands(id) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS products_category_id_idx ON products (category_id);
CREATE INDEX IF NOT EXISTS products_brand_id_idx ON products (brand_id);

CREATE TABLE IF NOT EXISTS pricing_tiers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  warranty_years integer CHECK (warranty_years IS NULL OR warranty_years >= 0),
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS customers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint REFERENCES companies(id) ON DELETE RESTRICT,
  name text NOT NULL,
  organization text,
  phone text,
  email text,
  address text,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS customers_company_name_idx ON customers (company_id, name);

CREATE TABLE IF NOT EXISTS activity_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES users(id) ON DELETE SET NULL,
  company_id bigint REFERENCES companies(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity_type text NOT NULL,
  entity_id text,
  summary text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  ip_address inet,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS activity_logs_created_idx ON activity_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS activity_logs_entity_idx ON activity_logs (entity_type, entity_id);

ALTER TABLE companies ADD COLUMN IF NOT EXISTS currency char(3) NOT NULL DEFAULT 'BDT';
ALTER TABLE companies ADD COLUMN IF NOT EXISTS vat_defaults jsonb NOT NULL DEFAULT '{}'::jsonb;

INSERT INTO roles (name, code, description) VALUES
  ('Super Admin', 'super-admin', 'Full system access'),
  ('Admin', 'admin', 'Administrative catalog and sales access'),
  ('Sales', 'sales', 'Quotation and customer access'),
  ('Accounts', 'accounts', 'Invoice and financial access'),
  ('Viewer', 'viewer', 'Read-only access')
ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description;

INSERT INTO permissions (code, description) VALUES
  ('manage_companies','Manage company profiles and settings'),
  ('manage_categories','Manage category hierarchy'),
  ('manage_brands','Manage brands and category assignments'),
  ('manage_products','Manage shared products and models'),
  ('manage_prices','Manage company-specific pricing'),
  ('manage_calculator_settings','Manage calculator configuration'),
  ('manage_quotations','Manage quotations'),
  ('manage_invoices','Manage invoices'),
  ('manage_templates','Manage quotation, invoice, and terms templates'),
  ('manage_users','Manage users and roles'),
  ('view_activity_logs','View activity logs')
ON CONFLICT (code) DO UPDATE SET description=EXCLUDED.description;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p WHERE r.code='super-admin'
ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code <> 'manage_users' WHERE r.code='admin'
ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code IN ('manage_quotations','manage_prices') WHERE r.code='sales'
ON CONFLICT DO NOTHING;
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r JOIN permissions p ON p.code IN ('manage_invoices','manage_quotations') WHERE r.code='accounts'
ON CONFLICT DO NOTHING;

INSERT INTO pricing_tiers (code,name,description,warranty_years,sort_order) VALUES
  ('default','Default','Standard price used by non-tiered products',NULL,0),
  ('gold','Gold','Existing standard LED tier',1,10),
  ('platinum','Platinum','Existing premium LED tier',2,20),
  ('diamond','Diamond','Existing top LED tier',3,30),
  ('cob','COB','Existing receiving-card COB variant',NULL,40)
ON CONFLICT (code) DO UPDATE SET name=EXCLUDED.name, description=EXCLUDED.description,
  warranty_years=EXCLUDED.warranty_years, sort_order=EXCLUDED.sort_order;

DO $$
DECLARE table_name text;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['roles','users','categories','brands','pricing_tiers','customers']
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I_updated_at ON %I', table_name, table_name);
    EXECUTE format('CREATE TRIGGER %I_updated_at BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()', table_name, table_name);
  END LOOP;
END $$;

COMMIT;
