BEGIN;

ALTER TABLE companies ADD COLUMN IF NOT EXISTS signatory_name text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS signatory_designation text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS signatory_company_name text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS signatory_phone text;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS signatory_email text;

CREATE TABLE IF NOT EXISTS company_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_id bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
  asset_type text NOT NULL CHECK (asset_type IN ('logo','site_logo','invoice_pad','seal','signature')),
  file_name text NOT NULL,
  mime_type text NOT NULL,
  content bytea NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (company_id, asset_type)
);

COMMIT;
